### ISSUE TITLE
Error running experiments

### ISSUE THREAD

**Issue by GhivvagoDamas** [messias077/ner_pt#1]
E ai cara, tudo bem? Como eu rodo devidamente os experimentos desse repositório? Sigo o readme e etc mas sempre tenho impedimentos! Poderia me ajudar?

**Comment by messias077** [comment]
Boa tarde! 

Primeiramente obrigado por estar tentando reproduzir os experimentos! Fiz uma readequação no repo para que os scripts rodem conforme está no readme.

Quanto aos embeddings, será necessário baixá-los (tem os links no código!).

Perdão pela falta de interatividade para rodar os experimentos... É que estou na correria aqui para fechar o mestrado e o foco foi rodar os experimentos! Infelizmente não é possivel criar uma interatividade melhor com os nossos scripts no momento.
